project: 
  type: website
  
website: 
  page-navigation: true
  title: "FlatSat Introduction Presentation" 
  site-url: "https://rlhoussaine.github.io/FlatSatIntro/" 
  
  repo-url: https://github.com/rlhoussaine/FlatSatIntro 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
    
  sidebar:
    logo: "images/bsvg.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.infiniteorbits.io/
        text: "infiniteorbits.io"
      - icon: github
        href: https://github.com/infiniteorbits
        text: "Infinite Orbits github"
      - icon: instagram
        href: https://www.instagram.com/infinite_orbits/?hl=en
        text: "IO Instagram"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: flatsat/endurance.qmd
        contents: 
          - flatsat/platform.qmd
          - flatsat/flatsat.qmd
          - flatsat/spacepackets.qmd
          - flatsat/yamcs.qmd
          - flatsat/swdev.qmd
      - learning-more.qmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
