---
title: End-to-End FlatSat Service Overview
subtitle: From Comprehensive Hardware Integration to Seamless Software Validation
---

## Welcome {#welcome}

Welcome to the Flatsat team! These upcoming pages serve as a supplement to the various meetings you'll attend upon joining, rather than replacing them. Here, we won’t cover the company's overall history, broader projects, or general onboarding, but will focus specifically on the activities tied to the Flatsat team and the Flatsat-related developments.

In summary, we’ll start with a brief introduction to the Endurance project to set the context, then discuss the purpose of developing a flatsat and its practical implementation within the project. Finally, we’ll explore the current testing phase regarding telecommunications between ground software and the flatsat components. We’ll begin with simple, direct communication over communication channels before advancing to a more complex setup that includes radio communication.

## How to Read This Document

The goal of this document is to start with a quick overview of the Endurance project and gradually zoom in on the Flatsat’s implementation, leading to the current activities where new team members can find their starting point. By following each page in sequence, you should gain a deeper understanding of how and why we are developing the flatsat.

## What’s Next?

After reading these pages, we’ll proceed to practical work and code-related tasks. The practical aspects are grouped in a developing library called the **Endurance FlatSat Library**. We have started drafting usage guides for installing the necessary sub-services to manage specific parts or components of the flatsat. You can find the latest drafted documents here (non-validated): [ReadTheDocs](https://endurance-flatsat-lib.readthedocs.io/en/develop/). Please use these guides as needed, but also make sure to raise tickets for any unclear or problematic steps.

## Your Contribution to This Document

The aim is to keep evolving this document over time, beginning with feedback on areas that need correction or addition as you settle in. Later on, you’re encouraged to clone the repository and add new content. The overall goal of this document is to provide any new team member with all the technical information needed to understand the broader purpose of our activities and the functioning of systems and subsystems.

Additionally, I’ve included some basic methods for collaborative work on software development projects. As the team grows, it will be necessary to update or add elements so anyone can adhere to our standards for code quality, reviews, ticketing, or broader workflows. 

This is also an opportunity to add, in a dedicated section, implemented software elements that may be beneficial to the entire company (e.g., how to create GitHub Actions).

## About

This document was created with **Quarto**, an open-source publishing system that allows users to generate and maintain beautifully formatted documents, websites, blogs, and presentations directly from markdown and Jupyter notebooks. Quarto’s versatility in supporting scientific and technical communication makes it an excellent choice for documenting complex projects like Flatsat. It enables you to combine text, code, and outputs seamlessly, creating a comprehensive and interactive resource for our team.

For more information on Quarto and how to use it to enhance your documentation projects, visit [Quarto’s website](https://quarto.org/).